using UnityEngine;

public class OpenHandGestureTrigger : MonoBehaviour
{
    public OVRHand ovrHand;
    public Transform uiPanel;
    public float pinchThreshold = 0.3f;
    public float requiredHoldTime = 0.4f;

    private float gestureTimer = 0f;
    public float proximityThreshold = 0.1f; // 5cm è·ç¦»åˆ¤å®š

    private float elapsedTime = 0f;
    private bool delayPassed = false;

    void Update()
    {
        // è®¡æ—¶
        if (!delayPassed)
        {
            elapsedTime += Time.deltaTime;
            if (elapsedTime >= 10f)
            {
                delayPassed = true;
            }
            else
            {
                return; // ç­‰å¾… 10 ç§’å‰ï¼Œä¸æ‰§è¡Œåç»­é€»è¾‘
            }
        }

        if (ovrHand == null || !ovrHand.IsTracked) return;

        bool allFingersOpen = isHover(ovrHand);

        // è·å–æ‰‹çš„ä½ç½®
        Vector3 handPos = ovrHand.transform.position;

        // è·å– cube çš„å·¦ä¾§é¢ä¸–ç•Œåæ ‡
        // Vector3 cubeLeftWorldPos = uiPanel.transform.position - uiPanel.transform.right * (uiPanel.transform.lossyScale.x / 2f);

        // è®¡ç®—ä¸å·¦ä¾§é¢çš„è·ç¦»
        float distanceToLeft = Vector3.Distance(handPos, uiPanel.position);

        // Debug
        Debug.Log("ğŸ–ï¸ æ‰‹å¼ å¼€: " + allFingersOpen + "ï¼Œè·ç¦» Cube å·¦ä¾§: " + distanceToLeft);
        // Debug.Log("ğŸ–ï¸ æ‰‹å¼ å¼€: " + handPos + cubeLeftWorldPos + Color.red);

        if (allFingersOpen && distanceToLeft < proximityThreshold)
        {
            gestureTimer += Time.deltaTime;
            if (gestureTimer > requiredHoldTime)
            {
                Debug.Log("ğŸ–ï¸ è¯†åˆ«åˆ°å¼ æ‰‹æ‰‹åŠ¿ï¼Œæ˜¾ç¤º UI");                
            }
        }
        else
        {
            gestureTimer = 0f;
        }
    }

    private bool isHover(OVRHand hand)
    {
        Debug.Log("IsOneGesture Index: " + hand.GetFingerPinchStrength(OVRHand.HandFinger.Index));
        Debug.Log("IsOneGesture Thumb: " + hand.GetFingerPinchStrength(OVRHand.HandFinger.Thumb));
        Debug.Log("IsOneGesture Middle: " + hand.GetFingerPinchStrength(OVRHand.HandFinger.Middle));
        Debug.Log("IsOneGesture Ring: " + hand.GetFingerPinchStrength(OVRHand.HandFinger.Ring));
        Debug.Log("IsOneGesture Pinky: " + hand.GetFingerPinchStrength(OVRHand.HandFinger.Pinky));            

        // é£ŸæŒ‡æœªæåˆï¼ˆ= ä¼¸å‡ºï¼‰
        bool indexExtended = hand.GetFingerPinchStrength(OVRHand.HandFinger.Index) < 0.1f;
        bool ThumbExtended = hand.GetFingerPinchStrength(OVRHand.HandFinger.Thumb) < 0.1f;
        bool MiddleExtended = hand.GetFingerPinchStrength(OVRHand.HandFinger.Middle) < 0.1f;
        bool RingExtended = hand.GetFingerPinchStrength(OVRHand.HandFinger.Ring) < 0.1f;
        bool PinkyExtended = hand.GetFingerPinchStrength(OVRHand.HandFinger.Pinky) < 0.1f;


        return indexExtended && ThumbExtended && MiddleExtended && RingExtended && PinkyExtended;
    }
}
